"""Exceptions"""

import logging
import json


class GenericError(Exception):
    """
    Used to simplify the implemention of exception messages that do not appear often
    """

    def __init__(self, message, status_code=500):
        Exception.__init__(self)
        self.message = message
        self.status_code = status_code

    def get_response(self):
        return {
            "message": self.message,
            "status_code": self.status_code
        }, self.status_code


class DockerError(Exception):
    """
    Can package and forward most error messages generated by the docker API
    """

    def __init__(self, error):
        Exception.__init__(self)
        self.content = json.loads(error.response.content.decode('ascii'))
        self.status_code = error.response.status_code

    def get_response(self):
        response = self.content
        response.update({
            "status_code": self.status_code,
        })
        return response, self.status_code


class InsufficientResourcesError(Exception):
    """Insufficient Resources
    Indicates that one or more resources are insufficiently available for the desired action.
    """

    def __init__(self, message="No message provided", status_code=400, insufficient_resources=[]):

        Exception.__init__(self)
        logging.info('InsufficientResourcesError: ' +
                     str(message))
        self.message = message
        self.insufficient_resources = insufficient_resources
        self.status_code = status_code

    def get_response(self):
        return {
            "message": self.message,
            "status_code":self.status_code,
            "insufficient_resources":self.insufficient_resources
        }, self.status_code


class TypeError(Exception):
    """
    Used when a user passes an additional Key in a request body that is not supported
    """

    def __init__(self, error, status_code=400):
        Exception.__init__(self)
        self.message = json.dumps(error.args)
        self.status_code = status_code

    def get_response(self):
        return {
            "message": self.message,
            "status_code": self.status_code
        }, self.status_code
